import { allow, deny, rule, shield } from 'trpc-shield';
import { Context } from '../context';
import { RolesNames } from '../routers/auth/interfaces/roles.interface';
import { verifyConektaSignature } from '../routers/utils/verifyConektaSignature';
import { verifyStripeSignature } from '../routers/utils/verifyStripeSignature';
import { TRPCError } from '@trpc/server';

const isAdmin = rule<Context>()(
  async (ctx) => ctx.session?.user?.role === RolesNames.admin,
);

const isLoggedIn = rule<Context>()(async (ctx) => Boolean(ctx.session?.user));

const isValidConektaSignature = rule<Context>()(async ({ req }) =>
  verifyConektaSignature(req, JSON.parse(req.body as any)),
);

const isValidStripeSignature = rule<Context>()(async ({ req }) =>
  verifyStripeSignature(req, process.env.STRIPE_WH_SECRET as string),
);

export const permissions = shield<Context>(
  {
    query: {
    list: isLoggedIn,
    download: isLoggedIn,
    quota: isLoggedIn,
    demo: isLoggedIn,
    login: allow,
    register: allow,
    me: isLoggedIn,
    'comms.getEmailPreferences': isLoggedIn,
    getEmailPreferences: isLoggedIn,
    search: isLoggedIn,
    catalogStats: isLoggedIn,
    'ftp.catalogStats': isLoggedIn,
    findByCode: isLoggedIn,
    ownOrders: isLoggedIn,
    getActiveUsers: isAdmin,
    getCancelledUsers: isAdmin,
    getInactiveUsers: isAdmin,
    findManyOrdersWithUsers: isAdmin,
    ownDescargas: isLoggedIn,
    subscribeWithStripe: isLoggedIn,
    listStripeCards: isLoggedIn,
    getProducts: isLoggedIn,
    myDirDownloads: isLoggedIn,
    getCheckoutLogs: isAdmin,
    getCheckoutLeads: isAdmin,
    getAnalyticsFunnelOverview: isAdmin,
    getAnalyticsDailySeries: isAdmin,
    getAnalyticsAttribution: isAdmin,
    getAnalyticsBusinessMetrics: isAdmin,
    getAnalyticsUxQuality: isAdmin,
    getAnalyticsTopEvents: isAdmin,
    getAnalyticsAlerts: isAdmin,
    getAnalyticsCancellationReasons: isAdmin,
    getAnalyticsLiveSnapshot: isAdmin,
    getAnalyticsCrmDashboard: isAdmin,
    aggregateConfig: isAdmin,
    aggregateCountries: isAdmin,
    aggregateCupons: isAdmin,
    aggregateCuponsUsed: isAdmin,
    aggregateDescargasUser: isAdmin,
    aggregateFtpQuotaLimits: isAdmin,
    aggregateFtpQuotatAlliesHistory: isAdmin,
    aggregateFtpUser: isAdmin,
    aggregateLoginHistory: isAdmin,
    aggregateOrders: isAdmin,
    aggregatePlans: isAdmin,
    aggregateRoles: isAdmin,
    aggregateUserFiles: isAdmin,
    aggregateUsers: isAdmin,
    findFirstConfig: isLoggedIn,
    findFirstCountries: isAdmin,
    findFirstCupons: isAdmin,
    findFirstCuponsUsed: isAdmin,
    findFirstDescargasUser: isAdmin,
    findFirstFtpQuotaLimits: isAdmin,
    findFirstFtpQuotatAlliesHistory: isAdmin,
    findFirstFtpUser: isAdmin,
    findFirstLoginHistory: isAdmin,
    findFirstOrders: isAdmin,
    findFirstPlans: isAdmin,
    findFirstRoles: isAdmin,
    findFirstUserFiles: isAdmin,
    findFirstUsers: isAdmin,
    findManyConfig: isAdmin,
    findManyCountries: isAdmin,
    findManyCupons: isAdmin,
    findManyCuponsUsed: isAdmin,
    findManyDescargasUser: isAdmin,
    findManyFtpQuotaLimits: isAdmin,
    findManyFtpQuotatAlliesHistory: isAdmin,
    findManyFtpUser: isAdmin,
    findManyLoginHistory: isAdmin,
    findManyOrders: isAdmin,
    findManyPlans: allow,
    getTrialConfig: allow,
    getPublicPricingConfig: allow,
    getUpgradeOptions: isLoggedIn,
    resolveCheckoutPlan: allow,
    getPublicBestPlans: allow,
    findManyRoles: isAdmin,
    findManyUserFiles: isAdmin,
    findManyUsers: isAdmin,
    countUsers: isAdmin,
    findUniqueConfig: isAdmin,
    findUniqueCountries: isAdmin,
    findUniqueCupons: isAdmin,
    findUniqueCuponsUsed: isAdmin,
    findUniqueDescargasUser: isAdmin,
    findUniqueFtpQuotaLimits: isAdmin,
    findUniqueFtpQuotatAlliesHistory: isAdmin,
    findUniqueFtpUser: isAdmin,
    findUniqueLoginHistory: isAdmin,
    findUniqueOrders: isAdmin,
    findUniquePlans: isAdmin,
    findUniqueRoles: isAdmin,
    findUniqueUserFiles: isAdmin,
    findUniqueUsers: isAdmin,
    groupByConfig: isAdmin,
    groupByCountries: isAdmin,
    groupByCupons: isAdmin,
    groupByCuponsUsed: isAdmin,
    groupByDescargasUser: isAdmin,
    groupByFtpQuotaLimits: isAdmin,
    groupByFtpQuotatAlliesHistory: isAdmin,
    groupByFtpUser: isAdmin,
    groupByLoginHistory: isAdmin,
    groupByOrders: isAdmin,
    groupByPlans: isAdmin,
    groupByRoles: isAdmin,
    groupByUserFiles: isAdmin,
    groupByUsers: isAdmin,
    // Missing shielded procedures: be explicit to avoid silent `trpc-shield` fallback behavior.
    ls: isLoggedIn,
    downloadDir: isLoggedIn,
    getCurrentSubscriptionPlan: isLoggedIn,
    getConektaAvailability: allow,
    storage: isAdmin,
    getDownloadHistory: isAdmin,
    getRemainingGigas: isAdmin,
    getAutomationStatus: isAdmin,
    aggregateFtpquotatallies: isAdmin,
    groupByFtpquotatallies: isAdmin,
    findFirstConfigOrThrow: isAdmin,
    findFirstCountriesOrThrow: isAdmin,
    findFirstCuponsOrThrow: isAdmin,
    findFirstCuponsUsedOrThrow: isAdmin,
    findFirstDescargasUserOrThrow: isAdmin,
    findFirstFtpQuotaLimitsOrThrow: isAdmin,
    findFirstFtpquotatallies: isAdmin,
    findFirstFtpquotatalliesOrThrow: isAdmin,
    findFirstFtpQuotatAlliesHistoryOrThrow: isAdmin,
    findFirstFtpUserOrThrow: isAdmin,
    findFirstLoginHistoryOrThrow: isAdmin,
    findFirstOrdersOrThrow: isAdmin,
    findFirstPlansOrThrow: isAdmin,
    findFirstRolesOrThrow: isAdmin,
    findFirstUserFilesOrThrow: isAdmin,
    findFirstUsersOrThrow: isAdmin,
    findManyFtpQuotaLimitsByUser: isAdmin,
    findManyFtpquotatallies: isAdmin,
    findManyUsersWithPlan: isAdmin,
    findUniqueConfigOrThrow: isAdmin,
    findUniqueCountriesOrThrow: isAdmin,
    findUniqueCuponsOrThrow: isAdmin,
    findUniqueCuponsUsedOrThrow: isAdmin,
    findUniqueDescargasUserOrThrow: isAdmin,
    findUniqueFtpQuotaLimitsOrThrow: isAdmin,
    findUniqueFtpquotatallies: isAdmin,
    findUniqueFtpquotatalliesOrThrow: isAdmin,
    findUniqueFtpQuotatAlliesHistoryOrThrow: isAdmin,
    findUniqueFtpUserOrThrow: isAdmin,
    findUniqueLoginHistoryOrThrow: isAdmin,
    findUniqueOrdersOrThrow: isAdmin,
    findUniquePlansOrThrow: isAdmin,
    findUniqueRolesOrThrow: isAdmin,
    findUniqueUserFilesOrThrow: isAdmin,
    findUniqueUsersOrThrow: isAdmin,
  },
    mutation: {
    verifyPhone: isLoggedIn,
    sendVerificationCode: isLoggedIn,
    cancelDirDownload: isLoggedIn,
    'comms.updateEmailPreferences': isLoggedIn,
    updateEmailPreferences: isLoggedIn,
    addBlockedEmailDomain: isAdmin,
    addBlockedPhoneNumber: isAdmin,
    updatePlanInfo: isLoggedIn,
    removeInactiveUsers: isAdmin,
    changeSubscriptionPlan: isLoggedIn,
    blockUser: isAdmin,
    unblockUser: isAdmin,
    addManyChatTagToUser: isLoggedIn,
    createStripePlan: isAdmin,
    updateStripePlan: isAdmin,
    deleteStripePlan: isAdmin,
    createPaypalPlan: isAdmin,
    deactivatePaypalPlan: isAdmin,
    activatePlanForUser: isAdmin,
    removeBlockedEmailDomain: isAdmin,
    removeBlockedPhoneNumber: isAdmin,
    subscribeWithCardConekta: isLoggedIn,
    subscribeWithCashConekta: isLoggedIn,
    subscribeWithPayByBankConekta: isLoggedIn,
    subscribeWithOxxoStripe: isLoggedIn,
    conektaSubscriptionWebhook: isValidConektaSignature,
    stripeSubscriptionWebhook: isValidStripeSignature,
    subscribeWithPaypal: isLoggedIn,
    createStripeCheckoutSession: isLoggedIn,
    createPaypalOrder: isLoggedIn,
    cancelOrder: isLoggedIn,
    requestSubscriptionCancellation: isLoggedIn,
    impersonateUser: isAdmin,
    createNewPaymentMethod: isLoggedIn,
    setDefaultStripePm: isLoggedIn,
    createBillingPortalSession: isLoggedIn,
    removeStripeCard: isLoggedIn,
    buyMoreGB: isLoggedIn,
    createStripeCupon: isAdmin,
    deleteStripeCupon: isAdmin,
    updateStripeCupon: isAdmin,
    createOneConfig: isAdmin,
    createOneCountries: isAdmin,
    createOneCupons: isAdmin,
    createOneCuponsUsed: isAdmin,
    createOneDescargasUser: isAdmin,
    createOneFtpQuotaLimits: isAdmin,
    createOneFtpQuotatAlliesHistory: isAdmin,
    createOneFtpUser: isAdmin,
    createOneLoginHistory: isAdmin,
    createOneOrders: isAdmin,
    createOnePlans: isAdmin,
    createOneRoles: isAdmin,
    createOneUserFiles: isAdmin,
    createOneUsers: isAdmin,
    deleteManyConfig: isAdmin,
    deleteManyCountries: isAdmin,
    deleteManyCupons: isAdmin,
    deleteManyCuponsUsed: isAdmin,
    deleteManyDescargasUser: isAdmin,
    deleteManyFtpQuotaLimits: isAdmin,
    deleteManyFtpQuotatAlliesHistory: isAdmin,
    deleteManyFtpUser: isAdmin,
    deleteManyLoginHistory: isAdmin,
    deleteManyOrders: isAdmin,
    deleteManyPlans: isAdmin,
    deleteManyRoles: isAdmin,
    deleteManyUserFiles: isAdmin,
    deleteManyUsers: isAdmin,
    deleteOneConfig: isAdmin,
    deleteOneCountries: isAdmin,
    deleteOneCupons: isAdmin,
    deleteOneCuponsUsed: isAdmin,
    deleteOneDescargasUser: isAdmin,
    deleteOneFtpQuotaLimits: isAdmin,
    deleteOneFtpQuotatAlliesHistory: isAdmin,
    deleteOneFtpUser: isAdmin,
    deleteOneLoginHistory: isAdmin,
    deleteOneOrders: isAdmin,
    deleteOnePlans: isAdmin,
    deleteOneRoles: isAdmin,
    deleteOneUserFiles: isAdmin,
    deleteOneUsers: isAdmin,
    updateManyConfig: isAdmin,
    updateManyCountries: isAdmin,
    updateManyCupons: isAdmin,
    updateManyCuponsUsed: isAdmin,
    updateManyDescargasUser: isAdmin,
    updateManyFtpQuotaLimits: isAdmin,
    updateManyFtpQuotatAlliesHistory: isAdmin,
    updateManyFtpUser: isAdmin,
    updateManyLoginHistory: isAdmin,
    updateManyOrders: isAdmin,
    updateManyPlans: isAdmin,
    updateManyRoles: isAdmin,
    updateManyUserFiles: isAdmin,
    updateManyUsers: isAdmin,
    updateOneConfig: isAdmin,
    updateOneCountries: isAdmin,
    updateOneCupons: isAdmin,
    updateOneCuponsUsed: isAdmin,
    updateOneDescargasUser: isAdmin,
    updateOneFtpQuotaLimits: isAdmin,
    updateOneFtpQuotatAlliesHistory: isAdmin,
    updateOneFtpUser: isAdmin,
    updateOneLoginHistory: isAdmin,
    updateOneOrders: isAdmin,
    updateOnePlans: isAdmin,
    updateOneRoles: isAdmin,
    updateOneUserFiles: isAdmin,
    updateOneUsers: isAdmin,
    upsertOneConfig: isAdmin,
    upsertOneCountries: isAdmin,
    upsertOneCupons: isAdmin,
    upsertOneCuponsUsed: isAdmin,
    upsertOneDescargasUser: isAdmin,
    upsertOneFtpQuotaLimits: isAdmin,
    upsertOneFtpQuotatAlliesHistory: isAdmin,
    upsertOneFtpUser: isAdmin,
    upsertOneLoginHistory: isAdmin,
    upsertOneOrders: isAdmin,
    upsertOnePlans: isAdmin,
    upsertOneRoles: isAdmin,
    upsertOneUserFiles: isAdmin,
    upsertOneUsers: isAdmin,
    // Missing shielded procedures: be explicit to avoid silent `trpc-shield` fallback behavior.
    logout: isLoggedIn,
    claimManyChatHandoff: isLoggedIn,
    // Checkout lead logging is best-effort and can be called from public surfaces.
    // The procedure itself no-ops when there is no authenticated user.
    registerCheckoutLog: allow,
    sendFacebookEvent: isLoggedIn,
    addAdditionalGBToQuotaLimit: isAdmin,
    removeUserByAdminAction: isAdmin,
    adminAddManyChatTag: isAdmin,
    adminCreateOffer: isAdmin,
    adminMarkContacted: isAdmin,
    createManyConfig: isAdmin,
    createManyCountries: isAdmin,
    createManyCupons: isAdmin,
    createManyCuponsUsed: isAdmin,
    createManyDescargasUser: isAdmin,
    createManyFtpQuotaLimits: isAdmin,
    createManyFtpquotatallies: isAdmin,
    createManyFtpQuotatAlliesHistory: isAdmin,
    createManyFtpUser: isAdmin,
    createManyLoginHistory: isAdmin,
    createManyOrders: isAdmin,
    createManyPlans: isAdmin,
    createManyRoles: isAdmin,
    createManyUserFiles: isAdmin,
    createManyUsers: isAdmin,
    createOneFtpquotatallies: isAdmin,
    deleteManyFtpquotatallies: isAdmin,
    deleteOneFtpquotatallies: isAdmin,
    updateManyFtpquotatallies: isAdmin,
    updateOneFtpquotatallies: isAdmin,
    upsertOneFtpquotatallies: isAdmin,
  },
  },
  {
    // Default deny: every `shieldedProcedure` must have an explicit permission rule.
    fallbackRule: deny,
    // Ensure permission denials don't look like 500s in clients (better UX + clearer telemetry).
    fallbackError: new TRPCError({ code: 'FORBIDDEN', message: 'No autorizado' }),
  },
);
