import { allow, rule, shield } from 'trpc-shield';
import { Context } from '../context';
import { RolesNames } from '../routers/auth/interfaces/roles.interface';
import { verifyConektaSignature } from '../routers/utils/verifyConektaSignature';

const isAdmin = rule<Context>()(
  async (ctx) => ctx.session?.user?.role === RolesNames.admin,
);

const isLoggedIn = rule<Context>()(async (ctx) => Boolean(ctx.session?.user));

const isValidConektaSignature = rule<Context>()(async ({ req }) =>
  verifyConektaSignature(req, JSON.parse(req.body as any)),
);

export const permissions = shield<Context>({
  query: {
    list: isLoggedIn,
    download: isLoggedIn,
    quota: isLoggedIn,
    demo: isLoggedIn,
    login: allow,
    register: allow,
    me: isLoggedIn,
    findByCode: isLoggedIn,
    aggregateConfig: isAdmin,
    aggregateCountries: isAdmin,
    aggregateCupons: isAdmin,
    aggregateCuponsUsed: isAdmin,
    aggregateDescargasUser: isAdmin,
    aggregateFtpQuotaLimits: isAdmin,
    aggregateFtpQuotatAlliesHistory: isAdmin,
    aggregateFtpUser: isAdmin,
    aggregateLoginHistory: isAdmin,
    aggregateOrders: isAdmin,
    aggregatePlans: isAdmin,
    aggregateRoles: isAdmin,
    aggregateUserFiles: isAdmin,
    aggregateUsers: isAdmin,
    findFirstConfig: isAdmin,
    findFirstCountries: isAdmin,
    findFirstCupons: isAdmin,
    findFirstCuponsUsed: isAdmin,
    findFirstDescargasUser: isAdmin,
    findFirstFtpQuotaLimits: isAdmin,
    findFirstFtpQuotatAlliesHistory: isAdmin,
    findFirstFtpUser: isAdmin,
    findFirstLoginHistory: isAdmin,
    findFirstOrders: isAdmin,
    findFirstPlans: isAdmin,
    findFirstRoles: isAdmin,
    findFirstUserFiles: isAdmin,
    findFirstUsers: isAdmin,
    findManyConfig: isAdmin,
    findManyCountries: isAdmin,
    findManyCupons: isAdmin,
    findManyCuponsUsed: isAdmin,
    findManyDescargasUser: isAdmin,
    findManyFtpQuotaLimits: isAdmin,
    findManyFtpQuotatAlliesHistory: isAdmin,
    findManyFtpUser: isAdmin,
    findManyLoginHistory: isAdmin,
    findManyOrders: isAdmin,
    findManyPlans: allow,
    findManyRoles: isAdmin,
    findManyUserFiles: isAdmin,
    findManyUsers: isAdmin,
    findUniqueConfig: isAdmin,
    findUniqueCountries: isAdmin,
    findUniqueCupons: isAdmin,
    findUniqueCuponsUsed: isAdmin,
    findUniqueDescargasUser: isAdmin,
    findUniqueFtpQuotaLimits: isAdmin,
    findUniqueFtpQuotatAlliesHistory: isAdmin,
    findUniqueFtpUser: isAdmin,
    findUniqueLoginHistory: isAdmin,
    findUniqueOrders: isAdmin,
    findUniquePlans: isAdmin,
    findUniqueRoles: isAdmin,
    findUniqueUserFiles: isAdmin,
    findUniqueUsers: isAdmin,
    groupByConfig: isAdmin,
    groupByCountries: isAdmin,
    groupByCupons: isAdmin,
    groupByCuponsUsed: isAdmin,
    groupByDescargasUser: isAdmin,
    groupByFtpQuotaLimits: isAdmin,
    groupByFtpQuotatAlliesHistory: isAdmin,
    groupByFtpUser: isAdmin,
    groupByLoginHistory: isAdmin,
    groupByOrders: isAdmin,
    groupByPlans: isAdmin,
    groupByRoles: isAdmin,
    groupByUserFiles: isAdmin,
    groupByUsers: isAdmin,
  },
  mutation: {
    subscribeWithCardConekta: isLoggedIn,
    subscribeWithCashConekta: isLoggedIn,
    conektaSubscriptionWebhook: isValidConektaSignature,
    createOneConfig: isAdmin,
    createOneCountries: isAdmin,
    createOneCupons: isAdmin,
    createOneCuponsUsed: isAdmin,
    createOneDescargasUser: isAdmin,
    createOneFtpQuotaLimits: isAdmin,
    createOneFtpQuotatAlliesHistory: isAdmin,
    createOneFtpUser: isAdmin,
    createOneLoginHistory: isAdmin,
    createOneOrders: isAdmin,
    createOnePlans: isAdmin,
    createOneRoles: isAdmin,
    createOneUserFiles: isAdmin,
    createOneUsers: isAdmin,
    deleteManyConfig: isAdmin,
    deleteManyCountries: isAdmin,
    deleteManyCupons: isAdmin,
    deleteManyCuponsUsed: isAdmin,
    deleteManyDescargasUser: isAdmin,
    deleteManyFtpQuotaLimits: isAdmin,
    deleteManyFtpQuotatAlliesHistory: isAdmin,
    deleteManyFtpUser: isAdmin,
    deleteManyLoginHistory: isAdmin,
    deleteManyOrders: isAdmin,
    deleteManyPlans: isAdmin,
    deleteManyRoles: isAdmin,
    deleteManyUserFiles: isAdmin,
    deleteManyUsers: isAdmin,
    deleteOneConfig: isAdmin,
    deleteOneCountries: isAdmin,
    deleteOneCupons: isAdmin,
    deleteOneCuponsUsed: isAdmin,
    deleteOneDescargasUser: isAdmin,
    deleteOneFtpQuotaLimits: isAdmin,
    deleteOneFtpQuotatAlliesHistory: isAdmin,
    deleteOneFtpUser: isAdmin,
    deleteOneLoginHistory: isAdmin,
    deleteOneOrders: isAdmin,
    deleteOnePlans: isAdmin,
    deleteOneRoles: isAdmin,
    deleteOneUserFiles: isAdmin,
    deleteOneUsers: isAdmin,
    updateManyConfig: isAdmin,
    updateManyCountries: isAdmin,
    updateManyCupons: isAdmin,
    updateManyCuponsUsed: isAdmin,
    updateManyDescargasUser: isAdmin,
    updateManyFtpQuotaLimits: isAdmin,
    updateManyFtpQuotatAlliesHistory: isAdmin,
    updateManyFtpUser: isAdmin,
    updateManyLoginHistory: isAdmin,
    updateManyOrders: isAdmin,
    updateManyPlans: isAdmin,
    updateManyRoles: isAdmin,
    updateManyUserFiles: isAdmin,
    updateManyUsers: isAdmin,
    updateOneConfig: isAdmin,
    updateOneCountries: isAdmin,
    updateOneCupons: isAdmin,
    updateOneCuponsUsed: isAdmin,
    updateOneDescargasUser: isAdmin,
    updateOneFtpQuotaLimits: isAdmin,
    updateOneFtpQuotatAlliesHistory: isAdmin,
    updateOneFtpUser: isAdmin,
    updateOneLoginHistory: isAdmin,
    updateOneOrders: isAdmin,
    updateOnePlans: isAdmin,
    updateOneRoles: isAdmin,
    updateOneUserFiles: isAdmin,
    updateOneUsers: isAdmin,
    upsertOneConfig: isAdmin,
    upsertOneCountries: isAdmin,
    upsertOneCupons: isAdmin,
    upsertOneCuponsUsed: isAdmin,
    upsertOneDescargasUser: isAdmin,
    upsertOneFtpQuotaLimits: isAdmin,
    upsertOneFtpQuotatAlliesHistory: isAdmin,
    upsertOneFtpUser: isAdmin,
    upsertOneLoginHistory: isAdmin,
    upsertOneOrders: isAdmin,
    upsertOnePlans: isAdmin,
    upsertOneRoles: isAdmin,
    upsertOneUserFiles: isAdmin,
    upsertOneUsers: isAdmin,
  },
});
