// Centralized icon facade.
// We export Phosphor icons using the same names the app previously imported from `lucide-react`,
// so the rest of the codebase can switch icon sets with a mechanical import-path change.

export type { Icon as AppIcon, IconProps, IconWeight } from "@phosphor-icons/react";
export { IconContext, IconBase } from "@phosphor-icons/react";

export {
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowCircleUp as ArrowUpCircle,
  ArrowClockwise as RefreshCw,
  ArrowCounterClockwise as Undo2,
  ArrowSquareOut as ExternalLink,
  Bank as Landmark,
  Books as LibraryBig,
  BookOpen,
  BuildingOffice as Building2,
  Calendar as CalendarClock,
  Cards as WalletCards,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  ChartBar as BarChart3,
  Check,
  CheckCircle as CheckCircle2,
  Clock,
  Copy,
  CreditCard,
  CurrencyDollar as DollarSign,
  CursorClick as MousePointerClick,
  Database,
  DesktopTower as Server,
  DotsThreeVertical as MoreVertical,
  Download,
  DownloadSimple as FolderDown,
  EnvelopeSimple as Mail,
  Eye,
  EyeSlash as EyeOff,
  File,
  FileArchive,
  FileArrowDown as FileDown,
  FileAudio as FileMusic,
  FileText,
  FileVideo as FileVideoCamera,
  Folder,
  FolderOpen,
  FunnelSimple as Filter,
  Gauge,
  HardDrive as HardDriveDownload,
  HeartBreak as HeartCrack,
  Lightning as Zap,
  List as Menu,
  Stack as Layers3,
  Lock,
  LockOpen,
  Money as Banknote,
  MagnifyingGlass as Search,
  MagnifyingGlass as FolderSearch,
  Monitor,
  Moon,
  MusicNote as Music,
  Pause,
  Phone,
  Pencil,
  PencilSimple as Edit2,
  Play,
  PlayCircle as CirclePlay,
  Plus,
  Prohibit as Ban,
  Pulse as Activity,
  Question as HelpCircle,
  Question as CircleHelp,
  Receipt,
  Repeat,
  Shield,
  ShieldCheck,
  ShoppingCart,
  SignIn as LogIn,
  SignOut as LogOut,
  Sparkle as Sparkles,
  Spinner as Loader2,
  Storefront as Store,
  Sun,
  Tag as Ticket,
  Trash as Trash2,
  TrendUp as TrendingUp,
  User,
  UserCircle as UserRound,
  UserPlus,
  Users,
  Wallet,
  WifiSlash as WifiOff,
  Warning as AlertTriangle,
  X,
  XCircle,
} from "@phosphor-icons/react";

// Lucide had both `Unlock` and `LockOpen` in different places.
// In Phosphor we normalize both to `LockOpen`, keeping the old symbol name.
export { LockOpen as Unlock } from "@phosphor-icons/react";
