import { z } from 'zod';

export const UsersScalarFieldEnumSchema = z.enum([
  'id',
  'registered_on',
  'username',
  'password',
  'first_name',
  'last_name',
  'address',
  'birthdate',
  'email',
  'stripe_cusid',
  'conekta_cusid',
  'phone',
  'city',
  'role_id',
  'country_id',
  'profile_img',
  'active',
  'activationcode',
  'mc_id',
  'ip_registro',
  'token_expiration',
  'refresh_token',
]);
