import { z } from 'zod';

export const UsersScalarFieldEnumSchema = z.enum([
  'id',
  'registered_on',
  'username',
  'password',
  'first_name',
  'last_name',
  'address',
  'birthdate',
  'email',
  'stripe_cusid',
  'conekta_cusid',
  'phone',
  'city',
  'role_id',
  'country_id',
  'profile_img',
  'active',
  'activationcode',
  'mc_id',
  'ip_registro',
  'token_expiration',
  'refresh_token',
  'email_marketing_opt_in',
  'email_marketing_news_opt_in',
  'email_marketing_offers_opt_in',
  'email_marketing_digest_opt_in',
  'whatsapp_marketing_opt_in',
  'sms_marketing_opt_in',
  'marketing_opt_in_updated_at',
  'trial_used_at',
  'blocked',
  'verified'
]);
