export enum PaypalEvent {
  BILLING_SUBSCRIPTION_CANCELLED = 'BILLING.SUBSCRIPTION.CANCELLED',
  BILLING_SUBSCRIPTION_ACTIVATED = 'BILLING.SUBSCRIPTION.ACTIVATED',
  BILLING_SUBSCRIPTION_EXPIRED = 'BILLING.SUBSCRIPTION.EXPIRED',
  BILLING_SUBSCRIPTION_UPDATED = 'BILLING.SUBSCRIPTION.UPDATED',
  PAYMENT_SALE_COMPLETED = 'PAYMENT.SALE.COMPLETED',
  PAYMENT_SALE_DENIED = 'PAYMENT.SALE.DENIED',
}
