export interface GenreStats {
  name: string;
  files: number;
  gb: number;
}

const TOP_GENRES_STATS: Record<string, { files: number; gb: number }> = {
  "Reguetton": { files: 20_421, gb: 1_129.58 },
  "Electro": { files: 14_165, gb: 956.82 },
  "House": { files: 12_138, gb: 949.31 },
  "Hip Hop": { files: 11_960, gb: 674.09 },
  "Dembow": { files: 6_305, gb: 276.52 },
  "Pop Ingles": { files: 5_984, gb: 411.56 },
  "Retro Ingles Dance": { files: 5_743, gb: 385.8 },
  "Cumbia": { files: 5_549, gb: 362.48 },
  "Reggae": { files: 5_079, gb: 266.93 },
  "Salsa": { files: 4_725, gb: 273.88 },
  "Cubaton": { files: 4_625, gb: 246.31 },
  "Guaracha": { files: 4_555, gb: 468.43 },
  "Acapella In Out": { files: 4_083, gb: 223.03 },
  "Pop Latino Dance": { files: 4_069, gb: 254.28 },
  "Reggaeton": { files: 3_952, gb: 203.79 },
  "Alternativo": { files: 3_779, gb: 246.07 },
  "80's": { files: 3_684, gb: 237.78 },
  "Bachata": { files: 3_426, gb: 177.58 },
  "Transition": { files: 2_973, gb: 211.94 },
  "Country": { files: 2_840, gb: 151.62 },
  "Merengue": { files: 2_436, gb: 139.3 },
  "Cumbia Sonidera": { files: 2_200, gb: 174.06 },
  "Retro Ingles": { files: 2_153, gb: 145.61 },
  "Latino": { files: 1_984, gb: 114.51 },
};

const FALLBACK_GENRE_NAMES = [
  "Acapella In Out",
  "Afro House",
  "Afrobeat",
  "Alternativo",
  "Bachata",
  "Bachata Acapella",
  "Bachata Remix",
  "Bachata Rmx",
  "Baladas Inmortales",
  "Banda",
  "Banda Con Tuba",
  "Banda Movida",
  "Banda Movida Quebradita",
  "Bootleg",
  "Christmas Bachata",
  "Christmas Balada",
  "Christmas Banda",
  "Christmas Bomba Y Plena",
  "Christmas Cumbia",
  "Christmas Cumbia Sonidera",
  "Christmas Dembow",
  "Christmas Duranguense",
  "Christmas Grupero",
  "Christmas Hip Hop",
  "Christmas Jazz",
  "Christmas Kizomba",
  "Christmas Latin Hip Hop",
  "Christmas Latin House",
  "Christmas Latin Jazz",
  "Christmas Latin Pop",
  "Christmas Mariachi",
  "Christmas Merengue",
  "Christmas Moombahton",
  "Christmas Nortenos",
  "Christmas Pop",
  "Christmas R&B",
  "Christmas Reggae",
  "Christmas Reggaeton",
  "Christmas Salsa",
  "Christmas Spanish Rock",
  "Christmas Vallenato",
  "Classic House",
  "Classics",
  "Conteos 2025",
  "Corridos",
  "Costeñas Charanga Chilenas",
  "Country",
  "Cubaton",
  "Cumbia",
  "Cumbia Con Mariachi",
  "Cumbia Ecuador Peru Chile",
  "Cumbia Ecuador-Peru",
  "Cumbia Ecuador-Peru-Chile",
  "Cumbia Nortena",
  "Cumbia Norteña",
  "Cumbia Remix",
  "Cumbia Rmx",
  "Cumbia Sonidera",
  "Cumbia Sonora",
  "Cumbia Tropical",
  "Cumbia Wepa",
  "Cumbias Belicas",
  "Cumbias Colombianas",
  "Cumbias Ecuatorianas",
  "Cumbias Inmortales",
  "Cumbias Laguneras",
  "Cumbias Norteñas Light",
  "Cumbias Sonideras",
  "Cumbias Tropicales",
  "Cumbias Wepa",
  "Dance",
  "Dance Remix",
  "Decepcionados",
  "Dembow",
  "Despecho Tools",
  "Dubstep",
  "Duranguense",
  "EDM",
  "Electro",
  "Electro Dance",
  "Electro House",
  "Electro Latino",
  "Electro Pop",
  "Germany",
  "Gruperas",
  "Grupero",
  "Guaracha",
  "Hip Hop",
  "Hip Hop Urban",
  "Hip-Hop",
  "House",
  "Huapango",
  "Huapangos",
  "Huapangos Tribal",
  "Latin",
  "Latin House",
  "Latin Pop",
  "Latino",
  "Latino Urbano",
  "Mashup",
  "Mega Mixes",
  "Megamix",
  "Merengue",
  "Merengue Remix",
  "Merengue Rmx",
  "Modern Rock",
  "Moombahton",
  "Musica Infantil",
  "Navidad",
  "Norteñas",
  "Norteñas Sax",
  "Norteno",
  "Norteño",
  "Nortenos",
  "Nu Disco",
  "Old School Classics",
  "Pop",
  "Pop Ingles",
  "Pop Latino Dance",
  "Pop Top 40",
  "Progressive House",
  "Punta",
  "R&B",
  "Ranchero",
  "Rap",
  "Reggae",
  "Reggae Dancehall",
  "Reggaeton",
  "Reggaeton Acaeplla",
  "Reggaeton Old",
  "Regional",
  "Regional Mex Dance Club",
  "Regional Remix",
  "Reguetton",
  "Reguetton Old",
  "Reguetton Vs",
  "Retro",
  "Retro Club",
  "Retro En Espanol",
  "Retro En Español",
  "Retro Ingles",
  "Retro Ingles 00s",
  "Retro Ingles Dance",
  "Retro Ingles Dance 00's",
  "Retro Ingles Dance 00s",
  "Rhythmic Top 40",
  "Rock",
  "Rock Espanol",
  "Rock Español",
  "Rock Ingles",
  "Salsa",
  "Salsa Remix",
  "Salsa Rmx",
  "Sessiones Remix",
  "Tech House",
  "Techno",
  "Tierra Caliente",
  "Top 40",
  "Transiciones",
  "Transition",
  "Trap",
  "Twerk",
  "Urban",
  "Urbano",
  "Vallenato",
  "Zapateado",
  "01 Karaokes Enero 2024",
  "01 Karaokes Enero 2025",
  "02 Karaokes Febrero 2024",
  "02 Karaokes Febrero 2025",
  "03 Karaokes Marzo 2024",
  "03 Karaokes Marzo 2025",
  "04 Karaokes Abril 2024",
  "05 Karaokes Mayo 2024",
  "06 Karaokes Junio 2024",
  "07 Karaokes Julio 2024",
  "08 Karaokes Agosto 2024",
  "09 Karaokes Septiembre 2024",
  "10 Karaokes Octubre 2024",
  "11 Karaokes Noviembre 2024",
  "60's",
  "60s",
  "60's Remix",
  "60's Rmx",
  "70's",
  "70's Remix",
  "70's Rmx",
  "70s",
  "70s Remix",
  "70s Rmx",
  "70s Old School",
  "80's",
  "80's High Energy",
  "80's Remix",
  "80's Rmx",
  "80s",
  "80s High Energy",
  "80s Remix",
  "80s Rmx",
  "90's",
  "90's Latino",
  "90's Old School",
  "90's Remix",
  "90's Rmx",
  "90s",
  "90s Latino",
  "90s Old School",
  "90s Remix",
  "90s Rmx",
] as const;

export const FALLBACK_GENRES: GenreStats[] = FALLBACK_GENRE_NAMES.map((name) => ({
  name,
  files: TOP_GENRES_STATS[name]?.files ?? 0,
  gb: TOP_GENRES_STATS[name]?.gb ?? 0,
}));
